services:

  proxy:
    image: nginx:1.27
    volumes:
      - type: bind
        source: ./proxy/nginx.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
    ports:
      - 80:80
    depends_on:
      - agent
      - backend

  agent:
    image: ghcr.io/auth-policy-controller/agent:0.2.0
    command: run --addr :8090 /policy.yaml
    volumes:
      - type: bind
        source: ./agent/policy.yaml
        target: /policy.yaml
    ports:
      - 8090:8090

  backend:
    image: jmalloc/echo-server
    ports:
      - 8080:8080
